security:
  user:
    name: htcc
    password: 6h5K8dapxfFdVKAS

server:
  port: 8761

# edit defaultZone to eureka2:8762
# to run 2 instances on local
eureka:
  replica: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.replica}:8761/eureka
