server:
  port: 8202

security:
  user:
    name: admin
    password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka
  instance:
    hostname: eureka1

service:
  debugMode: true
  hazelcast:
    useHazelcast: false
    enableRest: true
    monitorLevel: "OFF"
    address: 127.0.0.1:5701

spring:
  datasource:
    schemaName: HTCC_Admin
    options: useSSL=false&zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8
    server: 127.0.0.1:3306
    url: jdbc:mysql://${spring.datasource.server}/${spring.datasource.schemaName}?${spring.datasource.options}
    username: ${security.user.name}
    password: ${security.user.password}
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
