server:
  port: 8202

security:
  user:
    name: admin
    password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka
  instance:
    hostname: eureka1

service:
  debugMode: true
  hazelcast:
    useHazelcast: false
    enableRest: true
    monitorLevel: "OFF"
    address: 127.0.0.1
    port: 5701

spring:
  datasource:
    schemaName: HTCC_Admin
    server: 127.0.0.1:3306
