security:
  user:
    name: admin
    password: admin

server:
  port: 8761

# edit register-with-eureka & fetch-registry -> true
# and defaultZone to eureka2:8762
# to run 2 instances on local
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@eureka1:8761/eureka
  instance:
    hostname: eureka1

