qrcode:
  hashKey: admin
  loadFromConfig: false
  companyId: VNG
  officeId: CAMPUS
  baseUrl: http://localhost:8761/api/employee
  methodName: /public/genqrcode
resetpassword:
  hashKey: admin
  baseUrl: http://localhost:8761/api/gateway
  methodName: /public/resetpassword/update
createorder:
  hashKey: admin
  baseUrl: http://localhost:8761/api/admin
  methodName: /public/createorder
submittrans:
  hashKey: admin
  baseUrl: http://localhost:8761/api/admin
  methodName: /public/submittrans
