zookeeper1:
    image: digitalwonderland/zookeeper
    container_name: zookeeper1
    environment:
        - ZOOKEEPER_ID=1
        - ZOOKEEPER_SERVER_1=10.25.96.3
        - ZOOKEEPER_SERVER_2=10.25.96.4
        - ZOOKEEPER_CLIENT_PORT=2181
    ports:
        - 2181:2181
        - 2888:2888
        - 3888:3888


zookeeper2:
    image: digitalwonderland/zookeeper
    container_name: zookeeper2
    environment:
        - ZOOKEEPER_ID=2
        - ZOOKEEPER_SERVER_1=10.25.96.3
        - ZOOKEEPER_SERVER_2=10.25.96.4
        - ZOOKEEPER_CLIENT_PORT=2181
    ports:
        - 2181:2181
        - 2888:2888
        - 3888:3888

kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    environment:
        - KAFKA_ADVERTISED_PORT=9092
        - KAFKA_ADVERTISED_HOST_NAME=10.25.96.3
        - KAFKA_ZOOKEEPER_CONNECT=10.25.96.3:2181,10.25.96.4:2181
        - KAFKA_LOG_RETENTION_BYTES=500000000
        - KAFKA_HEAP_OPTS="-Xmx384M -Xms256M"
    ports:
        - 9092:9092

kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    environment:
        - KAFKA_ADVERTISED_PORT=9092
        - KAFKA_ADVERTISED_HOST_NAME=10.25.96.4
        - KAFKA_ZOOKEEPER_CONNECT=10.25.96.3:2181,10.25.96.4:2181
        - KAFKA_LOG_RETENTION_BYTES=500000000
        - KAFKA_HEAP_OPTS="-Xmx384M -Xms256M"
    ports:
        - 9092:9092
